"""telefone e amail do cliente

Revision ID: 30af488a912f
Revises: 0034b3ef4a16
Create Date: 2024-05-27 17:43:15.301887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30af488a912f'
down_revision = '0034b3ef4a16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente', sa.Column('telefone', sa.String(length=11), nullable=True))
    op.add_column('cliente', sa.Column('email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cliente', 'email')
    op.drop_column('cliente', 'telefone')
    # ### end Alembic commands ###
