"""empty message

Revision ID: 3ed3e339f9b5
Revises: b0cb6addf01a
Create Date: 2024-05-07 10:12:10.321919

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ed3e339f9b5'
down_revision = 'b0cb6addf01a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cliente', 'nome',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('cliente', 'cpf',
               existing_type=mysql.VARCHAR(length=11),
               nullable=True)
    op.alter_column('cliente', 'data_nascimento',
               existing_type=sa.DATE(),
               nullable=True)
    op.add_column('movimento', sa.Column('quantidade', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movimento', 'quantidade')
    op.alter_column('cliente', 'data_nascimento',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('cliente', 'cpf',
               existing_type=mysql.VARCHAR(length=11),
               nullable=False)
    op.alter_column('cliente', 'nome',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
