"""update produto

Revision ID: 535744a80553
Revises: 3ed3e339f9b5
Create Date: 2024-05-07 10:41:56.589726

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '535744a80553'
down_revision = '3ed3e339f9b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimentos')
    op.drop_table('produtos')
    op.drop_table('clientes')
    op.alter_column('produto', 'data',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('produto', 'data',
               existing_type=sa.DATE(),
               nullable=False)
    op.create_table('clientes',
    sa.Column('cliente_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('produtos',
    sa.Column('produto_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('valor', mysql.DOUBLE(asdecimal=True), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('movimentos',
    sa.Column('cliente_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('produto_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('quantidade', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('valor', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('data', mysql.TEXT(), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
