"""empty message

Revision ID: 8f2f396fa3aa
Revises: 0669043a1da7
Create Date: 2024-05-08 14:26:34.814163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f2f396fa3aa'
down_revision = '0669043a1da7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente', sa.Column('quantidade', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cliente', 'quantidade')
    # ### end Alembic commands ###
