"""ajustando labels

Revision ID: b0cb6addf01a
Revises: daa6cac3adbc
Create Date: 2024-05-07 07:48:17.062445

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b0cb6addf01a'
down_revision = 'daa6cac3adbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movimento', 'descricao',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('movimento', 'cliente_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('produto', 'descricao',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('produto', 'tipo',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('produto', 'tipo',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('produto', 'descricao',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('movimento', 'cliente_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('movimento', 'descricao',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
