"""update cliente

Revision ID: f99987d8ba03
Revises: 535744a80553
Create Date: 2024-05-07 10:57:37.422922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f99987d8ba03'
down_revision = '535744a80553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente', sa.Column('quantidade', sa.Integer(), nullable=True))
    op.add_column('cliente', sa.Column('valor_total', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cliente', 'valor_total')
    op.drop_column('cliente', 'quantidade')
    # ### end Alembic commands ###
